python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_1 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_1 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_2 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_2 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_2 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_2 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_3 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_3 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_3 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=I3D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_3 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_1 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_1 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_2 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_2 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_2 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_2 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_3 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_3 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_3 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=RCN --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_3 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_1 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_1 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_2 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_2 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_2 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_2 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=16 --TRAIN_SUBSETS=train_3 --SEQ_LEN=16 --BATCH_SIZE=8
python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_3 --SEQ_LEN=16 --BATCH_SIZE=8

CUDA_VISIBLE_DEVICES=0 python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_1 --SEQ_LEN=8 --BATCH_SIZE=4
CUDA_VISIBLE_DEVICES=1 python main.py --MODE=gen_dets --MODEL_TYPE=C2D --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_1 --SEQ_LEN=8 --BATCH_SIZE=4
CUDA_VISIBLE_DEVICES=2 python main.py --MODE=gen_dets --MODEL_TYPE=RCLSTM --TEST_SEQ_LEN=8 --TRAIN_SUBSETS=train_3 --SEQ_LEN=8 --BATCH_SIZE=4
CUDA_VISIBLE_DEVICES=3 python main.py --MODE=gen_dets --MODEL_TYPE=RCLSTM --TEST_SEQ_LEN=32 --TRAIN_SUBSETS=train_3 --SEQ_LEN=8 --BATCH_SIZE=4
python main.py --MODE=train --MODEL_TYPE=RCLSTM --DATASET=ucf24 --VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1

CUDA_VISIBLE_DEVICES=0 python main.py --MODE=gen_dets --MODEL_TYPE=I3D --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=8 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10 && \
CUDA_VISIBLE_DEVICES=1 python main.py --MODE=gen_dets --MODEL_TYPE=I3D --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=32 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10

CUDA_VISIBLE_DEVICES=0 python main.py --MODE=gen_dets --MODEL_TYPE=C2D --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=8 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10 && \
CUDA_VISIBLE_DEVICES=0 python main.py --MODE=gen_dets --MODEL_TYPE=C2D --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=32 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10


CUDA_VISIBLE_DEVICES=2 python main.py --MODE=gen_dets --MODEL_TYPE=RCLSTM --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=8 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10 && \
CUDA_VISIBLE_DEVICES=2 python main.py --MODE=gen_dets --MODEL_TYPE=RCLSTM --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=32 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10

CUDA_VISIBLE_DEVICES=3 python main.py --MODE=gen_dets --MODEL_TYPE=RCN --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=8 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10 && \
CUDA_VISIBLE_DEVICES=2 python main.py --MODE=gen_dets --MODEL_TYPE=RCN --DATASET=ucf24 \
--VAL_SUBSETS=test --TRAIN_SUBSETS=train --SEQ_LEN=8 --BATCH_SIZE=4 --TEST_SEQ_LEN=32 \
--LR=0.00245 --MILESTONES=6,8 --MAX_EPOCHS=10 --VAL_STEP=1 --EVAL_EPOCHS=10